<?php $page = 'item'; $pageTitle = '证件规格'; require __DIR__ . '/header.php'; ?>
<div class="block block-rounded data-panel" id="item-block">
    <div class="block-content block-content-full border-bottom">
        <div class="row g-3 align-items-end">
            <div class="col-4"><label class="form-label">规格名称</label><div class="input-group"><span class="input-group-text"><i class="fa fa-search"></i></span><input type="text" class="form-control" id="item-name" placeholder="例如：一寸、护照、教师资格证"></div></div>
            <div class="col-2"><label class="form-label">状态</label><select class="form-select" id="item-status"><option value="0">全部</option><option value="1">开启</option><option value="2">关闭</option></select></div>
            <div class="col-auto"><button class="btn btn-primary" id="item-search">筛选</button></div>
            <div class="col-auto"><button class="btn btn-alt-secondary" id="item-reset">重置</button></div>
            <div class="col text-end"><button class="btn btn-alt-primary me-2" id="item-sync">同步规格</button><button class="btn btn-success" id="item-add">新增规格</button></div>
        </div>
    </div>
    <div class="block-content p-0"><div class="table-responsive fixed-table-area"><table class="table table-hover table-vcenter mb-0"><thead><tr><th class="ps-4">ID</th><th>规格</th><th>像素尺寸</th><th>物理尺寸</th><th>DPI</th><th>分类</th><th>状态</th><th class="text-end pe-4">操作</th></tr></thead><tbody id="item-list"></tbody></table></div></div>
    <div class="block-content block-content-full border-top"><div id="item-pagination"></div></div>
</div>

<div class="modal fade" id="item-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h3 class="modal-title h5 fw-bold" id="item-modal-title">新增规格</h3><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><form id="item-form" class="row g-3"><input type="hidden" id="item-id"><div class="col-12"><label class="form-label">规格名称</label><input class="form-control" id="item-form-name" maxlength="50" required></div><div class="col-3"><label class="form-label">宽（px）</label><input class="form-control" id="item-width-px" type="number" min="1" required></div><div class="col-3"><label class="form-label">高（px）</label><input class="form-control" id="item-height-px" type="number" min="1" required></div><div class="col-3"><label class="form-label">宽（mm）</label><input class="form-control" id="item-width-mm" type="number" min="1" required></div><div class="col-3"><label class="form-label">高（mm）</label><input class="form-control" id="item-height-mm" type="number" min="1" required></div><div class="col-3"><label class="form-label">分类</label><select class="form-select" id="item-category" required><option value="1">常用寸照</option><option value="2">各类签证</option><option value="3">各类证件</option></select></div><div class="col-3"><label class="form-label">DPI</label><input class="form-control" id="item-dpi" type="number" min="72" value="300" required></div><div class="col-3"><label class="form-label">图标</label><select class="form-select" id="item-icon" required><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option></select></div><div class="col-3"><label class="form-label">状态</label><select class="form-select" id="item-form-status" required><option value="1">开启</option><option value="2">关闭</option></select></div></form></div><div class="modal-footer"><button type="button" class="btn btn-alt-secondary" data-bs-dismiss="modal">取消</button><button type="button" class="btn btn-primary" id="item-save">保存</button></div></div></div></div>
<?php require __DIR__ . '/footer.php'; ?>
